---
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'html-app'
  tag: 'latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
  - script: |
    echo "===== Showing Dockerfile being used ====="
    pwd
    ls -la
    sed -n '1,20p' Dockerfile
  displayName: "Verify Dockerfile content"
    - task: Docker@2
      displayName: Build and Push Image
      inputs:
        command: buildAndPush
        repository: $(imageName)
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
	buildContext: '$(Build.SourcesDirectory)'
        containerRegistry: 'acr-connection'
	arguments: '--pull'
        tags: |
          $(tag)

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: AzureRmWebAppDeployment@4
      displayName: Deploy to App Service
      inputs:
        azureSubscription: 'azure-connection'
        appType: 'webAppContainer'
        WebAppName: 'appservicegit'
        DockerNamespace: 'appservicegit.azurecr.io'
        DockerRepository: 'html-app'
        DockerImageTag: 'latest'